const KEY='trivia-challenge-v1';
const ABC='ABCDEFGHILMNOPQRSTUVZ'.split('');
const TYPES={
  guess:'Indovina il personaggio',bomb:'Schiva la Bomba',said:"Chi l'ha detto",detail:'Occhio al dettaglio',quote:'Completa la Frase',chain:'Reazione a catena',labors:'Le Dieci Fatiche',guillotine:'Ghigliottina',pass:'Passaparola',jeopardy:'Jeopardy',sarabanda:'Sarabanda'
};
const id=p=>`${p}-${Math.random().toString(36).slice(2,8)}-${Date.now().toString(36)}`;
const clone=x=>JSON.parse(JSON.stringify(x));
const templates={
  guess:()=>({id:id('game'),type:'guess',title:'Indovina il personaggio',rounds:[{answer:'Nome personaggio',points:[1000,500,250,50],clues:['public/assets/personaggio-1.jpg','public/assets/personaggio-2.jpg','public/assets/personaggio-3.jpg','public/assets/personaggio-4.jpg']}]}),
  bomb:()=>({id:id('game'),type:'bomb',title:'Schiva la Bomba',question:'Trova i 16 elementi collegati alla domanda ed evita le 4 bombe.',pointsPerCorrect:50,items:Array.from({length:20},(_,i)=>({label:`Elemento ${i+1}`,image:'',isBomb:i>=16}))}),
  said:()=>({id:id('game'),type:'said',title:"Chi l'ha detto",points:100,questions:[{prompt:'Ascolta l audio e indovina il personaggio.',audio:'public/assets/frase-1.mp3',answer:'Personaggio',media:'public/assets/risposta.jpg'}]}),
  detail:()=>({id:id('game'),type:'detail',title:'Occhio al dettaglio',points:200,questions:[{detailImage:'public/assets/dettaglio.jpg',fullImage:'public/assets/scena-completa.jpg',answer:'Contesto completo della scena'}]}),
  quote:()=>({id:id('game'),type:'quote',title:'Completa la Frase',points:200,questions:[{partial:'Io sono tuo...',answer:'padre',source:'Star Wars'}]}),
  chain:()=>({id:id('game'),type:'chain',title:'Reazione a catena',topic:'Argomento',points:50,questions:Array.from({length:20},(_,i)=>({question:`Domanda sequenziale ${i+1}`,answer:`Risposta ${i+1}`}))}),
  labors:()=>({id:id('game'),type:'labors',title:'Le Dieci Fatiche',points:100,questions:Array.from({length:10},(_,i)=>({kind:['risposta secca','risposta multipla','elenco','spiegazione'][i%4],question:`Fatica ${i+1}`,options:i%4===1?['A','B','C','D']:[],answer:`Risposta ${i+1}`,explanation:'Spiegazione opzionale.'}))}),
  guillotine:()=>({id:id('game'),type:'guillotine',title:'Ghigliottina',points:200,words:['parola 1','parola 2','parola 3','parola 4','parola 5'],answer:'Risposta collegata'}),
  pass:()=>({id:id('game'),type:'pass',title:'Passaparola',difficulty:'facile',points:{facile:5,medio:5,difficile:20},bonus:{facile:200,medio:500,difficile:1000},questions:ABC.map(l=>({letter:l,question:`Con la ${l}: domanda`,answer:`Risposta con ${l}`,status:'pending'}))}),
  jeopardy:()=>({id:id('game'),type:'jeopardy',title:'Jeopardy',categories:['Anime','Cinema','Serie TV','Musica','Gaming'].map(name=>({name,clues:[100,200,300,400,500].map(value=>({value,question:`Domanda ${name} da ${value}`,answer:`Risposta ${name} ${value}`,used:false}))}))}),
  sarabanda:()=>({id:id('game'),type:'sarabanda',title:'Sarabanda',pointsTitle:25,pointsArtist:25,songs:[{audio:'public/assets/canzone-1.mp3',title:'Titolo brano',artist:'Artista'}]})
};
const defaults=()=>({players:[{id:id('p'),name:'Squadra A',score:0},{id:id('p'),name:'Squadra B',score:0}],games:Object.values(templates).map(f=>f()),history:[]});
let state=load(),view='play',gameId=state.games[0]?.id,playerId=state.players[0]?.id,cur={i:0,revealed:0,answer:false,selected:[],jeo:null},editing='';
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(s.games?.length&&s.players?.length)return s}}catch(e){console.warn(e)}return defaults()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function $(tag,attrs={},...kids){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(v===false||v==null)return;if(k==='class')n.className=v;else if(k==='html')n.innerHTML=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else n.setAttribute(k,v===true?'':v)});kids.flat().forEach(c=>{if(c!=null&&c!==false)n.append(c.nodeType?c:document.createTextNode(c))});return n}
function game(){return state.games.find(g=>g.id===gameId)||state.games[0]}
function player(){return state.players.find(p=>p.id===playerId)||state.players[0]}
function label(t){return TYPES[t]||t}
function toast(m){const t=$('div',{class:'toast'},m);document.body.append(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),220)},2200)}
function add(points,reason){const p=player();if(!p)return toast('Crea un giocatore.');p.score=Number(p.score||0)+Number(points||0);state.history.unshift({id:id('h'),playerName:p.name,points,reason,at:new Date().toISOString()});state.history=state.history.slice(0,80);save();toast(`${p.name}: ${points>0?'+':''}${points}`);render()}
function media(src,alt='media'){if(!src)return $('span',{class:'muted'},'Media non configurato');if(/\.(mp4|webm|mov)$/i.test(src))return $('video',{src,controls:true,playsinline:true});return $('img',{src,alt,loading:'lazy'})}
function audio(src){return src?$('audio',{src,controls:true}):$('span',{class:'muted'},'Audio non configurato')}
function top(){return $('header',{class:'top'},$('div',{class:'brand'},$('div',{class:'kicker'},'PowerPoint game → web tool'),$('h1',{},'Trivia Challenge'),$('p',{},'Crea minigiochi, presenta domande e indizi, assegna punti e correggi la classifica manualmente.')), $('nav',{class:'nav'},nav('play','Presenta'),nav('admin','Admin'),nav('scores','Punteggi')))}
function nav(v,t){return $('button',{class:view===v?'active':'',onclick:()=>{view=v;render()}},t)}
function render(){document.getElementById('app').replaceChildren(top(),view==='play'?play():view==='admin'?admin():scores())}
function selectGame(){const s=$('select',{onchange:e=>{gameId=e.target.value;cur={i:0,revealed:0,answer:false,selected:[],jeo:null};render()}});state.games.forEach(g=>s.append($('option',{value:g.id,selected:g.id===gameId},`${g.title} · ${label(g.type)}`)));return s}
function selectPlayer(){const s=$('select',{onchange:e=>{playerId=e.target.value;render()}});state.players.forEach(p=>s.append($('option',{value:p.id,selected:p.id===playerId},`${p.name} (${p.score} pt)`)));return s}
function play(){const g=game();if(!g)return $('main',{class:'panel'},$('h2',{},'Nessun minigioco'));return $('main',{class:'grid two'},$('section',{class:'panel stack'},$('div',{class:'row space'},$('div',{},$('div',{class:'kicker'},label(g.type)),$('h2',{},g.title||'Senza titolo')),$('button',{class:'btn ghost',onclick:()=>{cur={i:0,revealed:0,answer:false,selected:[],jeo:null};render()}},'Reset schermata')),$('div',{class:'grid two'},$('label',{},'Minigioco',selectGame()),$('label',{},'Giocatore attivo',selectPlayer())),renderGame(g)),$('aside',{class:'stack'},scoreboard(),history()))}
function scoreboard(){const ps=[...state.players].sort((a,b)=>(b.score||0)-(a.score||0));return $('section',{class:'panel stack'},$('h3',{},'Classifica'),...ps.map((p,i)=>$('div',{class:'score-card'},$('div',{},$('strong',{},`${i+1}. ${p.name}`),$('div',{class:'muted'},p.id===playerId?'attivo':'')),$('div',{class:'score'},p.score||0))))}
function history(){return $('section',{class:'panel stack'},$('h3',{},'Ultime assegnazioni'),...(state.history.length?state.history.slice(0,8).map(h=>$('div',{class:'score-card'},$('div',{},$('strong',{},h.playerName),$('div',{class:'muted'},h.reason)),$('div',{class:'score'},`${h.points>0?'+':''}${h.points}`))):[$('p',{class:'muted'},'Nessun punto assegnato.')]))}
function answer(text){return $('div',{class:`answer ${cur.answer?'on':''}`},cur.answer?$('strong',{},text||'Risposta non configurata'):'Risposta nascosta')}
function controls(g,ans,points,after){return $('div',{class:'stack'},$('div',{class:'row'},$('button',{class:'btn success',onclick:()=>{after?.();add(points,`${g.title}: risposta corretta`)}},`Corretta · +${points}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta')),answer(ans))}
function pager(total){return $('div',{class:'row'},$('button',{class:'btn',disabled:cur.i<=0,onclick:()=>{cur.i--;cur.answer=false;cur.revealed=0;cur.jeo=null;render()}},'← Precedente'),$('button',{class:'btn',disabled:cur.i>=total-1,onclick:()=>{cur.i++;cur.answer=false;cur.revealed=0;cur.jeo=null;render()}},'Successiva →'))}
function renderGame(g){return ({guess,bomb,said,detail,quote,chain,labors,guillotine,pass,jeopardy,sarabanda}[g.type]||unsupported)(g)}
function unsupported(g){return $('div',{class:'hero'},$('p',{class:'question'},`Tipo non supportato: ${g.type}`))}
function guess(g){const rs=g.rounds||[],r=rs[cur.i]||rs[0];if(!r)return $('div',{class:'hero'},'Nessun round.');const shown=Math.min(cur.revealed,r.clues?.length||0),pts=(r.points||[1000,500,250,50])[Math.max(0,shown-1)]||0;return $('div',{class:'hero'},$('p',{class:'big'},'Chi si nasconde dietro gli indizi?'),$('div',{class:'media-grid'},...(r.clues||[]).map((c,i)=>$('div',{class:`media ${i<shown?'':'hidden'}`},i<shown?media(typeof c==='string'?c:c.image,`Indizio ${i+1}`):''))),$('div',{class:'row'},$('button',{class:'btn primary',disabled:shown>=(r.clues?.length||0),onclick:()=>{cur.revealed++;render()}},'Rivela indizio'),$('button',{class:'btn success',disabled:shown===0,onclick:()=>add(pts,`${g.title}: ${shown} indizi`)},`Corretta · +${pts}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta')),answer(r.answer),pager(rs.length))}
function bomb(g){const sel=new Set(cur.selected||[]),items=g.items||[],ok=items.filter((it,i)=>sel.has(i)&&!it.isBomb).length,bad=items.filter((it,i)=>sel.has(i)&&it.isBomb).length;return $('div',{class:'hero'},$('p',{class:'question'},g.question||'Evita le bombe.'),$('div',{class:'row'},$('span',{class:'muted'},`Corrette: ${ok}`),$('span',{class:'muted'},`Bombe: ${bad}`)),$('div',{class:'tiles'},...items.map((it,i)=>$('button',{class:`tile ${sel.has(i)?(it.isBomb?'bomb':'ok'):''}`,onclick:()=>{sel.has(i)?sel.delete(i):sel.add(i);cur.selected=[...sel];render()}},it.image?media(it.image,it.label):null,$('span',{},it.label||`Elemento ${i+1}`)))),$('div',{class:'row'},$('button',{class:'btn success',onclick:()=>add(ok*(g.pointsPerCorrect||50),`${g.title}: ${ok} elementi corretti`)},`Assegna ${ok*(g.pointsPerCorrect||50)} pt`),$('button',{class:'btn',onclick:()=>{cur.selected=[];render()}},'Svuota'),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi bombe':'Mostra bombe')),cur.answer?$('div',{class:'answer on'},'Bombe: '+items.filter(x=>x.isBomb).map(x=>x.label).join(', ')):null)}
function linear(g,list,fn){const q=list[cur.i]||list[0];return q?$('div',{class:'stack'},fn(q),pager(list.length)):$('div',{class:'hero'},'Nessun contenuto.')}
function said(g){return linear(g,g.questions||[],q=>$('div',{class:'hero'},$('p',{class:'question'},q.prompt||'Ascolta e indovina.'),audio(q.audio),cur.answer?$('div',{class:'media'},media(q.media,q.answer)):null,controls(g,q.answer,g.points||100)))}
function detail(g){return linear(g,g.questions||[],q=>$('div',{class:'hero'},$('p',{class:'question'},'Da quale scena arriva questo dettaglio?'),$('div',{class:'media'},media(cur.answer?q.fullImage:q.detailImage,q.answer)),controls(g,q.answer,g.points||200)))}
function quote(g){return linear(g,g.questions||[],q=>$('div',{class:'hero'},$('p',{class:'question'},`“${q.partial||'Citazione parziale'}”`),q.source?$('p',{class:'muted'},q.source):null,controls(g,q.answer,g.points||200)))}
function chain(g){return linear(g,g.questions||[],q=>$('div',{class:'hero'},$('div',{class:'kicker'},g.topic||'Argomento'),$('p',{class:'question'},q.question),controls(g,q.answer,g.points||50)))}
function labors(g){return linear(g,g.questions||[],q=>$('div',{class:'hero'},$('div',{class:'kicker'},q.kind||'tipologia'),$('p',{class:'question'},q.question),q.options?.length?$('div',{class:'tiles'},...q.options.map(o=>$('div',{class:'tile'},o))):null,controls(g,`${q.answer||''}${q.explanation?' · '+q.explanation:''}`,g.points||100)))}
function guillotine(g){return $('div',{class:'hero'},$('p',{class:'question'},'Trova la parola collegata a tutte e cinque.'),$('div',{class:'tiles'},...(g.words||[]).map(w=>$('div',{class:'tile'},w))),controls(g,g.answer,g.points||200))}
function pass(g){const qs=g.questions||[],q=qs[cur.i]||qs[0],d=g.difficulty||'facile',pts=g.points?.[d]??5,bonus=g.bonus?.[d]??0,all=qs.length&&qs.every(x=>x.status==='correct');if(!q)return $('div',{class:'hero'},'Nessuna domanda.');return $('div',{class:'hero'},$('div',{class:'row space'},$('div',{},$('div',{class:'kicker'},`Difficoltà ${d}`),$('p',{class:'question'},`${q.letter}. ${q.question}`)),$('div',{class:'score'},`${pts} pt`)),$('div',{class:'letters'},...qs.map((x,i)=>$('button',{class:`letter ${x.status==='correct'?'ok':x.status==='wrong'?'wrong':x.status==='pass'?'pass':''}`,onclick:()=>{cur.i=i;cur.answer=false;render()}},x.letter))),$('div',{class:'row'},$('button',{class:'btn success',onclick:()=>{q.status='correct';add(pts,`${g.title}: lettera ${q.letter}`)}},`Corretta · +${pts}`),$('button',{class:'btn danger',onclick:()=>{q.status='wrong';save();render()}},'Sbagliata'),$('button',{class:'btn warn',onclick:()=>{q.status='pass';save();render()}},'Passo'),all?$('button',{class:'btn primary',onclick:()=>add(bonus,`${g.title}: bonus ${d}`)},`Bonus · +${bonus}`):null,$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta')),answer(q.answer),pager(qs.length))}
function jeopardy(g){const cats=g.categories||[];if(cur.jeo){const c=cats[cur.jeo.c],cl=c?.clues?.[cur.jeo.q];if(cl)return $('div',{class:'hero'},$('div',{class:'kicker'},`${c.name} · ${cl.value} punti`),$('p',{class:'question'},cl.question),controls(g,cl.answer,cl.value,()=>{cl.used=true;cur.jeo=null;save()}),$('button',{class:'btn ghost',onclick:()=>{cur.jeo=null;render()}},'Torna al tabellone'))}return $('div',{class:'hero'},$('div',{class:'tiles'},...cats.map((c,ci)=>$('div',{class:'stack'},$('div',{class:'tile'},c.name),...(c.clues||[]).map((cl,qi)=>$('button',{class:`tile ${cl.used?'used':''}`,disabled:cl.used,onclick:()=>{cur.jeo={c:ci,q:qi};cur.answer=false;render()}},cl.value))))))}
function sarabanda(g){return linear(g,g.songs||[],s=>$('div',{class:'hero'},$('p',{class:'question'},'Indovina titolo e autore della canzone.'),audio(s.audio),$('div',{class:'row'},$('button',{class:'btn success',onclick:()=>add(g.pointsTitle||25,`${g.title}: titolo`)},`Titolo · +${g.pointsTitle||25}`),$('button',{class:'btn success',onclick:()=>add(g.pointsArtist||25,`${g.title}: autore`)},`Autore · +${g.pointsArtist||25}`),$('button',{class:'btn primary',onclick:()=>add((g.pointsTitle||25)+(g.pointsArtist||25),`${g.title}: completa`)},'Completa · +50'),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta')),answer(`${s.title||'Titolo'} · ${s.artist||'Artista'}`)))}
function admin(){const sel=$('select',{id:'type',onchange:preview});Object.entries(TYPES).forEach(([v,l])=>sel.append($('option',{value:v},l)));const title=$('input',{id:'title',value:'Nuovo minigioco',oninput:()=>{if(!editing)preview()}}),ta=$('textarea',{id:'json'});setTimeout(preview);return $('main',{class:'grid two'},$('section',{class:'panel stack'},$('h2',{},'Admin minigiochi'),$('p',{class:'muted'},'Crea o modifica i contenuti in JSON. I media possono stare in public/assets/ oppure essere URL esterni.'),$('div',{class:'grid two'},$('label',{},'Tipo minigioco',sel),$('label',{},'Titolo',title)),$('label',{},'Contenuto JSON',ta),$('div',{class:'row'},$('button',{class:'btn primary',onclick:saveEditor},editing?'Salva modifiche':'Crea minigioco'),$('button',{class:'btn',onclick:()=>{editing='';preview()}},'Nuovo da template'),$('button',{class:'btn',onclick:exportData},'Esporta JSON'),$('label',{class:'btn ghost'},'Importa JSON',$('input',{type:'file',accept:'application/json',style:'display:none',onchange:importData}))),playersAdmin()),$('aside',{class:'panel stack'},$('h3',{},'Minigiochi salvati'),...state.games.map(g=>$('div',{class:'score-card'},$('div',{},$('strong',{},g.title),$('div',{class:'muted'},label(g.type))),$('div',{class:'row'},$('button',{class:'btn',onclick:()=>edit(g.id)},'Modifica'),$('button',{class:'btn',onclick:()=>dup(g.id)},'Duplica'),$('button',{class:'btn danger',onclick:()=>del(g.id)},'Elimina'))))))}
function preview(){const type=document.getElementById('type')?.value||'guess',title=document.getElementById('title')?.value||'Nuovo minigioco',ta=document.getElementById('json');if(!ta)return;const g=templates[type]();g.title=title;ta.value=JSON.stringify(g,null,2)}
function saveEditor(){try{const g=JSON.parse(document.getElementById('json').value);g.id=g.id||id('game');g.title=document.getElementById('title').value.trim()||g.title;const i=state.games.findIndex(x=>x.id===(editing||g.id));i>=0?state.games[i]=g:state.games.unshift(g);gameId=g.id;editing='';save();toast('Minigioco salvato');render()}catch(e){toast('JSON non valido: '+e.message)}}
function edit(gid){const g=state.games.find(x=>x.id===gid);if(!g)return;editing=gid;render();document.getElementById('type').value=g.type;document.getElementById('title').value=g.title||'';document.getElementById('json').value=JSON.stringify(g,null,2)}
function dup(gid){const g=clone(state.games.find(x=>x.id===gid));g.id=id('game');g.title+=' copia';state.games.unshift(g);save();render()}
function del(gid){const g=state.games.find(x=>x.id===gid);if(!g||!confirm(`Eliminare “${g.title}”?`))return;state.games=state.games.filter(x=>x.id!==gid);gameId=state.games[0]?.id;save();render()}
function playersAdmin(){return $('section',{class:'stack'},$('h3',{},'Giocatori'),$('div',{class:'row'},$('input',{id:'pname',placeholder:'Nome squadra o giocatore'}),$('button',{class:'btn success',onclick:()=>{const v=document.getElementById('pname').value.trim();if(!v)return toast('Inserisci un nome.');const p={id:id('p'),name:v,score:0};state.players.push(p);playerId=p.id;save();render()}},'Aggiungi')),...state.players.map(p=>$('div',{class:'score-card'},$('input',{value:p.name,onchange:e=>{p.name=e.target.value;save();render()}}),$('button',{class:'btn danger',onclick:()=>{if(state.players.length<2)return toast('Deve restare almeno un giocatore.');state.players=state.players.filter(x=>x.id!==p.id);playerId=state.players[0]?.id;save();render()}},'Rimuovi'))))}
function scores(){return $('main',{class:'grid two'},$('section',{class:'panel stack'},$('h2',{},'Gestione manuale punteggi'),$('p',{class:'muted'},'Correggi punteggi, assegna bonus o togli punti in qualsiasi momento.'),$('table',{class:'table'},$('thead',{},$('tr',{},$('th',{},'Giocatore'),$('th',{},'Punti'),$('th',{},'Azioni'))),$('tbody',{},...state.players.map(p=>$('tr',{},$('td',{},p.name),$('td',{},$('input',{type:'number',value:p.score||0,onchange:e=>{p.score=Number(e.target.value||0);save();render()}})),$('td',{},$('div',{class:'row'},...[-100,-50,50,100,200,500,1000].map(v=>$('button',{class:'btn',onclick:()=>{playerId=p.id;add(v,'correzione manuale')}},v>0?`+${v}`:v)))))))),$('div',{class:'row'},$('button',{class:'btn danger',onclick:()=>{if(confirm('Azzerare tutti i punteggi?')){state.players.forEach(p=>p.score=0);state.history=[];save();render()}}},'Azzera tutto'),$('button',{class:'btn',onclick:()=>{state.history=[];save();render()}},'Svuota storico'))),scoreboard())}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=$('a',{href:url,download:`trivia-challenge-${new Date().toISOString().slice(0,10)}.json`});document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=JSON.parse(r.result);if(!s.games?.length||!s.players?.length)throw Error('Il file deve contenere games e players.');state=s;gameId=state.games[0].id;playerId=state.players[0].id;save();render();toast('Dati importati')}catch(err){toast('Import fallito: '+err.message)}};r.readAsText(f)}
render();
