const KEY='trivia-challenge-v2';
const LEGACY_KEY='trivia-challenge-v1';
const ABC='ABCDEFGHILMNOPQRSTUVZ'.split('');
const TYPES={
  guess:'Indovina il personaggio',bomb:'Schiva la Bomba',said:"Chi l'ha detto",detail:'Occhio al dettaglio',quote:'Completa la Frase',chain:'Reazione a catena',labors:'Le Dieci Fatiche',guillotine:'Ghigliottina',pass:'Passaparola',jeopardy:'Jeopardy',sarabanda:'Sarabanda'
};
const MENU_ORDER=['guess','bomb','jeopardy','pass','said','detail','quote','chain','labors','guillotine','sarabanda'];
const REFERENCE_IMAGES=[
  '1. Schermata Principale.png','2. Lista Anime.png','3. Schermata Poteri Giocatore 1.png','4. Schermata Poteri Giocatore 2.png','5. Schermata Poteri Giocatore 3.png','6. Punti.png','7. Schermata Minigioco 1.png','8. Schermata Minigioco 2.png','11. Schermata Minigioco 3.png','12. Schermata Minigioco 4.png','14. Schermata Minigioco 5.png','17. Schermata Minigioco 6.png','20. Schermata Minigioco 7.png','25. Schermata Minigioco 8.png','28. Schermata Minigioco 9.png','33. Schermata Schermata Minigioco 10.png','36. Schermata Minigioco 11.png'
];
const id=p=>`${p}-${Math.random().toString(36).slice(2,8)}-${Date.now().toString(36)}`;
const clone=x=>JSON.parse(JSON.stringify(x));
const animeList=['Attack on Titans','Berserk','Bleach','Chainsaw Man','Code Geass','Death Note','Demon Slayer','Dragon Ball','Frieren','Hunter X Hunter','Jujutsu Kaisen','Made in Abyss','My Hero Academia','Naruto','One Piece','One Punch Man','Overlord','Pokemon','Seven Deadly Sins','Vinland Saga'];
const powers=[
  {player:'Livio',name:'Mussolivio non vuole',text:"Rendi nulla la risposta di un avversario e impediscigli di prendere punti. Massimo due utilizzi."},
  {player:'Livio',name:'The Wolf of Avezzano',text:'Se rispondi correttamente, ottieni un bonus extra deciso dal presentatore.'},
  {player:'Melia',name:'Don Meliadolf',text:'Puoi aiutare un avversario rispondendo al posto suo: se la risposta è corretta, entrambi prendete punti.'},
  {player:'Melia',name:'Bodyguard personale',text:'Una protezione speciale ti salva da una penalità o da un furto punti.'},
  {player:'Maggi',name:'In medio stat virtus',text:'Se al termine di un minigioco sei esattamente secondo, ottieni 200 punti.'},
  {player:'Maggi',name:'Freebooter',text:'Rubi una possibilità o un piccolo bonus a un avversario, a discrezione del presentatore.'}
];
const templates={
  guess:()=>({id:id('game'),type:'guess',title:'Indovina il personaggio',menuTitle:'INDOVINA IL PERSONAGGIO',rounds:[{answer:'Nome personaggio',points:[1000,500,250,50],clues:[{label:'1000',image:'public/assets/personaggio-1.jpg'},{label:'500',image:'public/assets/personaggio-2.jpg'},{label:'250',image:'public/assets/personaggio-3.jpg'},{label:'50',image:'public/assets/personaggio-4.jpg'}]}]}),
  bomb:()=>({id:id('game'),type:'bomb',title:'Schiva la Bomba',menuTitle:'SCHIVA LA BOMBA!',question:'Trova i 16 elementi collegati alla domanda ed evita le 4 bombe.',pointsPerCorrect:50,items:Array.from({length:20},(_,i)=>({label:`Elemento ${i+1}`,image:'',isBomb:i>=16}))}),
  said:()=>({id:id('game'),type:'said',title:"Chi l'ha detto",menuTitle:"CHI L'HA DETTO",points:100,questions:[{prompt:'Ascolta l audio e indovina il personaggio.',audio:'public/assets/frase-1.mp3',answer:'Personaggio',media:'public/assets/risposta.jpg'}]}),
  detail:()=>({id:id('game'),type:'detail',title:'Occhio al dettaglio',menuTitle:'OCCHIO AL DETTAGLIO',points:200,questions:[{detailImage:'public/assets/dettaglio.jpg',fullImage:'public/assets/scena-completa.jpg',answer:'Contesto completo della scena'}]}),
  quote:()=>({id:id('game'),type:'quote',title:'Completa la Frase',menuTitle:'COMPLETA LA FRASE',points:200,questions:[{partial:'Io sono tuo...',answer:'padre',source:'Star Wars'}]}),
  chain:()=>({id:id('game'),type:'chain',title:'Reazione a catena',menuTitle:'REAZIONE A CATENA',topic:'Argomento',points:50,questions:Array.from({length:20},(_,i)=>({question:`Domanda sequenziale ${i+1}`,answer:`Risposta ${i+1}`}))}),
  labors:()=>({id:id('game'),type:'labors',title:'Le Dieci Fatiche',menuTitle:'LE DIECI FATICHE',points:100,questions:Array.from({length:10},(_,i)=>({kind:['risposta secca','risposta multipla','elenco','spiegazione'][i%4],question:`Fatica ${i+1}`,options:i%4===1?['A','B','C','D']:[],answer:`Risposta ${i+1}`,explanation:'Spiegazione opzionale.'}))}),
  guillotine:()=>({id:id('game'),type:'guillotine',title:'Ghigliottina',menuTitle:'GHIGLIOTTINA',points:200,words:['parola 1','parola 2','parola 3','parola 4','parola 5'],answer:'Risposta collegata'}),
  pass:()=>({id:id('game'),type:'pass',title:'Passaparola',menuTitle:'PASSAPAROLA',difficulty:'facile',points:{facile:5,medio:10,difficile:20},bonus:{facile:200,medio:500,difficile:1000},questions:ABC.map(l=>({letter:l,question:`Con la ${l}: domanda`,answer:`Risposta con ${l}`,status:'pending'}))}),
  jeopardy:()=>({id:id('game'),type:'jeopardy',title:'Jeopardy',menuTitle:'JEOPARDY',categories:['Anime','Cinema','Serie TV','Musica','Gaming'].map(name=>({name,clues:[100,200,300,400,500].map(value=>({value,question:`Domanda ${name} da ${value}`,answer:`Risposta ${name} ${value}`,used:false}))}))}),
  sarabanda:()=>({id:id('game'),type:'sarabanda',title:'Sarabanda',menuTitle:'SARABANDA',pointsTitle:25,pointsArtist:25,songs:[{audio:'public/assets/canzone-1.mp3',title:'Titolo brano',artist:'Artista'}]})
};
const defaults=()=>({
  title:'TRIVIA CHALLENGE',
  subtitle:'ANIME EDITION',
  players:[{id:id('p'),name:'LIVIO',score:1560},{id:id('p'),name:'MELIA',score:980},{id:id('p'),name:'MAGGI',score:820}],
  games:Object.values(templates).map(f=>f()),
  library:animeList,
  powers,
  history:[]
});
let state=load(),view='show',gameId=state.games[0]?.id,playerId=state.players[0]?.id,cur={screen:'hub',i:0,revealed:0,answer:false,selected:[],jeo:null},editing='';
function load(){for(const key of [KEY,LEGACY_KEY]){try{const raw=localStorage.getItem(key);if(raw){const s=JSON.parse(raw);if(s.games?.length&&s.players?.length)return hydrate(s)}}catch(e){console.warn(e)}}return defaults()}
function legacyHydrate(s){s.title=s.title||'TRIVIA CHALLENGE';s.subtitle=s.subtitle||'ANIME EDITION';s.library=s.library?.length?s.library:animeList;s.powers=s.powers?.length?s.powers:powers;s.history=s.history||[];s.games=(s.games||[]).map(g=>({...g,menuTitle:g.menuTitle||g.title||label(g.type)}));return s}
function legacySave(){localStorage.setItem(KEY,JSON.stringify(state))}
function $(tag,attrs={},...kids){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(v===false||v==null)return;if(k==='class')n.className=v;else if(k==='html')n.innerHTML=v;else if(k==='style')n.setAttribute('style',v);else if(k==='value')n.value=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else n.setAttribute(k,v===true?'':v)});kids.flat(Infinity).forEach(c=>{if(c!=null&&c!==false)n.append(c.nodeType?c:document.createTextNode(c))});return n}
function game(){return state.games.find(g=>g.id===gameId)||state.games[0]}
function player(){return state.players.find(p=>p.id===playerId)||state.players[0]}
function label(t){return TYPES[t]||t}
function toast(m){const t=$('div',{class:'toast'},m);document.body.append(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),220)},2200)}
function legacyAdd(points,reason){const p=player();if(!p)return toast('Crea un giocatore.');p.score=Number(p.score||0)+Number(points||0);state.history.unshift({id:id('h'),playerName:p.name,points:Number(points||0),reason,at:new Date().toISOString()});state.history=state.history.slice(0,120);save();toast(`${p.name}: ${points>0?'+':''}${points}`);render()}
function legacyMedia(src,alt='media'){if(!src)return $('span',{class:'muted'},'Media non configurato');if(/\.(mp4|webm|mov)$/i.test(src))return $('video',{src,controls:true,playsinline:true});return $('img',{src,alt,loading:'lazy'})}
function audio(src){return src?$('audio',{src,controls:true}):$('span',{class:'muted'},'Audio non configurato')}
function top(){return $('header',{class:'app-top'},$('div',{},$('div',{class:'kicker'},'PowerPoint-style game master'),$('h1',{},'Trivia Challenge Studio')),$('nav',{class:'app-nav'},nav('show','Show'),nav('admin','Admin'),nav('scores','Punteggi')))}
function nav(v,t){return $('button',{class:view===v?'active':'',onclick:()=>{view=v;if(v==='show'&&!cur.screen)cur.screen='hub';render()}},t)}
function render(){document.getElementById('app').replaceChildren(top(),view==='show'?show():view==='admin'?admin():scores())}
function resetStage(screen='hub'){cur={screen,i:0,revealed:0,answer:false,selected:[],jeo:null};render()}
function selectGame(){const s=$('select',{onchange:e=>{gameId=e.target.value;resetStage('game')}});state.games.forEach(g=>s.append($('option',{value:g.id,selected:g.id===gameId},`${g.title} · ${label(g.type)}`)));return s}
function selectPlayer(){const s=$('select',{onchange:e=>{playerId=e.target.value;render()}});state.players.forEach(p=>s.append($('option',{value:p.id,selected:p.id===playerId},`${p.name} (${p.score} pt)`)));return s}
function show(){
  const content=cur.screen==='hub'?hub():cur.screen==='points'?pointsScreen():cur.screen==='library'?libraryScreen():cur.screen==='powers'?powersScreen():gameScreen();
  return $('main',{class:'show-layout'},stage(content));
}
function stage(content){return $('section',{class:'ppt-stage'},stageToolbar(),$('div',{class:'stage-content'},content),hostHud(),bottomScores())}
function stageToolbar(){return $('div',{class:'stage-toolbar'},$('button',{class:'icon-btn',title:'Home',onclick:()=>resetStage('hub')},'⌂'),$('div',{class:'stage-title'},state.title||'TRIVIA CHALLENGE'),$('div',{class:'stage-actions'},$('button',{class:'mini-tab',onclick:()=>resetStage('library')},'LISTA ANIME'),$('button',{class:'mini-tab',onclick:()=>resetStage('powers')},'POTERI'),$('button',{class:'mini-tab',onclick:()=>resetStage('points')},'PUNTI'),$('button',{class:'icon-btn',title:'Reset schermata',onclick:()=>{cur={...cur,i:0,revealed:0,answer:false,selected:[],jeo:null};render()}},'↻')))}
function hostHud(){return null}
function bottomScores(){return $('div',{class:'bottom-scorebar'},...state.players.map(p=>$('button',{class:`player-chip ${p.id===playerId?'selected':''}`,onclick:()=>{playerId=p.id;render()}},$('span',{},p.name),$('strong',{},p.score||0))))}
function hub(){const groups=MENU_ORDER.map(t=>state.games.find(g=>g.type===t)).filter(Boolean);return $('div',{class:'hub-screen'},$('div',{class:'hero-title'},$('div',{class:'kicker'},state.subtitle||'Game edition'),$('h2',{},state.title||'TRIVIA CHALLENGE')), $('div',{class:'menu-board'},...groups.map(g=>$('button',{class:'ppt-button menu-button',onclick:()=>{gameId=g.id;resetStage('game')}},g.menuTitle||g.title))))}
function pointsScreen(){const values=[-250,-100,-25,-5,5,10,25,50,100,250,500,1000];return $('div',{class:'points-screen'},$('h2',{},'PUNTI'),$('div',{class:'points-columns'},...state.players.map(p=>$('div',{class:'points-card'},$('h3',{},p.name+':'),$('div',{class:'mega-score'},p.score||0),$('div',{class:'score-buttons'},...values.map(v=>$('button',{class:`score-btn ${v>0?'plus':'minus'}`,onclick:()=>{playerId=p.id;add(v,'pannello punti')}},String(v)))),$('button',{class:'btn danger',onclick:()=>{p.score=0;state.history.unshift({id:id('h'),playerName:p.name,points:0,reason:'reset giocatore',at:new Date().toISOString()});save();render()}},`Reset ${p.name}`))))) }
function libraryScreen(){return $('div',{class:'library-screen'},$('h2',{},'LISTA ANIME'),$('div',{class:'library-grid'},...state.library.map(x=>$('button',{class:'ppt-button library-tile'},x))))}
function powersScreen(){return $('div',{class:'powers-screen'},$('h2',{},'POTERI'),$('div',{class:'power-grid'},...state.powers.map(p=>$('article',{class:'power-card'},$('div',{class:'power-owner'},p.player),$('h3',{},p.name),$('p',{},p.text))))) }
function gameScreen(){const g=game();if(!g)return $('div',{class:'intro-screen'},$('h2',{},'Nessun minigioco'));return $('div',{class:'game-shell'},$('div',{class:'game-ribbon'},label(g.type)),renderGame(g))}
function answer(text){return $('div',{class:`answer ${cur.answer?'on':''}`},cur.answer?$('strong',{},text||'Risposta non configurata'):'Risposta nascosta')}
function legacyControls(g,ans,points,after){return $('div',{class:'host-actions'},$('button',{class:'btn success',onclick:()=>{after?.();add(points,`${g.title}: risposta corretta`)}},`Corretta · +${points}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta'),answer(ans))}
function pager(total){return $('div',{class:'pager'},$('button',{class:'btn',disabled:cur.i<=0,onclick:()=>{cur.i--;cur.answer=false;cur.revealed=0;cur.jeo=null;render()}},'←'),$('span',{},`${Math.min(cur.i+1,total||1)} / ${total||1}`),$('button',{class:'btn',disabled:cur.i>=total-1,onclick:()=>{cur.i++;cur.answer=false;cur.revealed=0;cur.jeo=null;render()}},'→'))}
function renderGame(g){return ({guess,bomb,said,detail,quote,chain,labors,guillotine,pass,jeopardy,sarabanda}[g.type]||unsupported)(g)}
function unsupported(g){return $('div',{class:'intro-screen'},$('h2',{},`Tipo non supportato: ${g.type}`))}
function legacyGuess(g){const rs=g.rounds||[],r=rs[cur.i]||rs[0];if(!r)return $('div',{class:'intro-screen'},'Nessun round.');const clues=(r.clues||[]).map(c=>typeof c==='string'?{label:'?',image:c}:c),shown=Math.min(cur.revealed,clues.length),pts=(r.points||[1000,500,250,50])[Math.max(0,shown-1)]||0;return $('div',{class:'guess-screen'},$('div',{class:'guess-grid'},...clues.map((c,i)=>$('button',{class:`guess-tile ${i<shown?'revealed':'covered'}`,onclick:()=>{if(i>=shown){cur.revealed=Math.max(cur.revealed,i+1);render()}}},i<shown?media(c.image,`Indizio ${i+1}`):$('span',{},c.label||r.points?.[i]||'?')))), $('div',{class:'host-actions'},$('button',{class:'btn primary',disabled:shown>=clues.length,onclick:()=>{cur.revealed++;render()}},'Rivela'),$('button',{class:'btn success',disabled:shown===0,onclick:()=>add(pts,`${g.title}: ${shown} indizi`)},`Corretta · +${pts}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta')),answer(r.answer),pager(rs.length))}
function legacyBomb(g){const sel=new Set(cur.selected||[]),items=g.items||[],ok=items.filter((it,i)=>sel.has(i)&&!it.isBomb).length,bad=items.filter((it,i)=>sel.has(i)&&it.isBomb).length;return $('div',{class:'bomb-screen'},$('div',{class:'bomb-question'},g.question||'Evita le bombe.'),$('div',{class:'bomb-grid'},...items.map((it,i)=>$('button',{class:`bomb-tile ${sel.has(i)?(it.isBomb?'bomb':'ok'):''}`,onclick:()=>{sel.has(i)?sel.delete(i):sel.add(i);cur.selected=[...sel];render()}},it.image?media(it.image,it.label):$('span',{},it.label||`Elemento ${i+1}`)))), $('div',{class:'host-actions'},$('span',{class:'pill'},`Corrette ${ok}`),$('span',{class:'pill'},`Bombe ${bad}`),$('button',{class:'btn success',onclick:()=>add(ok*(g.pointsPerCorrect||50),`${g.title}: ${ok} elementi corretti`)},`Assegna ${ok*(g.pointsPerCorrect||50)} pt`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi bombe':'Mostra bombe')),cur.answer?$('div',{class:'answer on'},'Bombe: '+items.filter(x=>x.isBomb).map(x=>x.label).join(', ')):null)}
function linear(g,list,fn){const q=list[cur.i]||list[0];return q?$('div',{class:'linear-screen'},fn(q),pager(list.length)):$('div',{class:'intro-screen'},'Nessun contenuto.')}
function stageMediaControls(){return $('div',{class:'ppt-media-controls'},$('button',{class:'media-btn'},'<<'),$('button',{class:'media-btn'},'||'),$('button',{class:'media-btn'},'>'))}
function scorePods(values,reason){return $('div',{class:'ppt-score-pods'},...state.players.map(p=>$('section',{class:`ppt-score-pod ${p.id===playerId?'selected':''}`},$('button',{class:'ppt-score-name',onclick:()=>{playerId=p.id;render()}},`${p.name}: ${p.score||0}`),$('div',{class:'ppt-score-buttons'},...values.map(v=>$('button',{onclick:()=>{playerId=p.id;add(v,reason)}},`+ ${v}`))))))}
function said(g){
  const qs=Array.from({length:10},(_,i)=>g.questions?.[i]||{prompt:`Audio ${i+1}`,audio:'',answer:''}),q=qs[cur.i]||qs[0],key=`said-${cur.i}`;
  return $('div',{class:'said-board-screen'},
    $('div',{class:'said-audio-board'},...qs.map((item,i)=>$('div',{class:`said-audio-row ${i===cur.i?'current':''}`},
      $('button',{class:'said-index',onclick:()=>{cur.i=i;cur.answer=false;render()}},i+1),
      $('div',{class:'said-audio-card'},item.audio?audio(item.audio):$('button',{onclick:()=>{cur.i=i;cur.answer=false;render()}},'AUDIO'))
    ))),
    $('aside',{class:'said-side'},
      $('div',{class:'said-answer-card'},cur.answer?cleanText(q.answer,'RISPOSTA'):'?'),
      $('div',{class:'said-number-grid'},...qs.map((_,i)=>$('button',{class:i===cur.i?'current':'',onclick:()=>{cur.i=i;cur.answer=false;render()}},i+1))),
      scorePods([g.points||100],`${g.title}: punti rapidi`),
      $('div',{class:'host-actions'},$('button',{class:'btn success',disabled:hasAwarded(key),onclick:()=>awardOnce(g.points||100,`${g.title}: audio ${cur.i+1}`,key)},hasAwarded(key)?'Assegnata':`Corretta · +${g.points||100}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi':'Mostra risposta'))
    ),
    $('div',{class:'said-footer'},$('div',{class:'chain-timer'},'00:00'),stageMediaControls())
  )
}
function detail(g){
  const qs=Array.from({length:5},(_,i)=>g.questions?.[i]||{detailImage:'',fullImage:'',answer:`Dettaglio ${i+1}`}),q=qs[cur.i]||qs[0],key=`detail-${cur.i}`;
  return $('div',{class:'detail-board-screen'},
    $('div',{class:'detail-side-index'},...qs.map((_,i)=>$('button',{class:i===cur.i?'current':'',onclick:()=>{cur.i=i;cur.answer=false;render()}},i+1))),
    $('div',{class:'detail-frame'},media(cur.answer?q.fullImage:q.detailImage,q.answer)),
    $('aside',{class:'detail-side'},
      $('div',{class:'detail-answer-card'},cur.answer?cleanText(q.answer,'RISPOSTA'):'?'),
      $('div',{class:'chain-timer'},'00:00'),
      stageMediaControls(),
      scorePods([g.points||200],`${g.title}: punti rapidi`),
      $('div',{class:'host-actions'},$('button',{class:'btn success',disabled:hasAwarded(key),onclick:()=>awardOnce(g.points||200,`${g.title}: dettaglio ${cur.i+1}`,key)},hasAwarded(key)?'Assegnata':`Corretta · +${g.points||200}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi':'Mostra risposta'))
    )
  )
}
function quote(g){const qs=g.questions?.length?g.questions:templates.quote().questions,rows=Array.from({length:Math.max(5,qs.length)},(_,i)=>qs[i]||{partial:`${['Prima','Seconda','Terza','Quarta','Quinta'][i]||`${i+1}a`} citazione`,answer:''}),q=rows[cur.i]||rows[0],key=`quote-${cur.i}-${playerId}`,done=hasAwarded(key);return $('div',{class:'quote-board-screen'},$('div',{class:'ppt-label'},'PUNTI'),$('div',{class:'quote-board'},...state.players.map(p=>$('section',{class:'quote-player-column'},$('button',{class:`ppt-title-card ${p.id===playerId?'selected':''}`,onclick:()=>{playerId=p.id;render()}},`COMPLETA LA FRASE, ${p.name}`),...rows.map((item,i)=>$('button',{class:`ppt-row-card ${i===cur.i&&p.id===playerId?'current':''}`,onclick:()=>{playerId=p.id;cur.i=i;cur.answer=false;render()}},cur.answer&&i===cur.i&&p.id===playerId?cleanText(item.answer,'RISPOSTA'):cleanText(item.partial,`${['PRIMA','SECONDA','TERZA','QUARTA','QUINTA'][i]||`${i+1}A`} CITAZIONE`)))))),controls(g,q.answer,g.points||200,key))}
function chain(g){const source=g.questions?.length?g.questions:templates.chain().questions,steps=Array.from({length:20},(_,i)=>source[i]||{question:`Domanda ${i+1}`,answer:''}),q=steps[cur.i]||steps[0],key=`chain-${cur.i}`,done=hasAwarded(key);const row=(item,i)=>{const active=i===cur.i,revealed=item.status==='correct'||(active&&cur.answer),text=revealed?cleanText(item.answer,item.question):active?cleanText(item.question,''):'';return $('button',{class:`chain-step ${active?'current':''} ${revealed?'revealed':''}`,onclick:()=>{cur.i=i;cur.answer=false;render()}},$('span',{class:'chain-number'},String(i+1)),$('span',{class:'chain-text'},text),i<19?$('span',{class:'chain-arrow'},'▼'):null)};return $('div',{class:'chain-board-screen'},$('div',{class:'chain-columns'},$('div',{class:'chain-column'},...steps.slice(0,10).map((item,i)=>row(item,i))),$('div',{class:'chain-turn'},'↺'),$('div',{class:'chain-column'},...steps.slice(10,20).map((item,i)=>row(item,i+10)))), $('div',{class:'chain-footer'},$('div',{class:'chain-timer'},'00:00'),$('div',{class:'chain-media-controls'},$('button',{class:'media-btn'},'◀'),$('button',{class:'media-btn'},'Ⅱ'),$('button',{class:'media-btn'},'▶')),$('div',{class:'chain-lives'},$('span',{},'♥'),$('span',{},'♥'),$('span',{},'♥'))),$('div',{class:'host-actions'},$('button',{class:'btn success',disabled:done,onclick:()=>awardOnce(g.points||50,`${g.title}: step ${cur.i+1}`,key,()=>{q.status='correct'})},done?'Assegnata':`Corretta · +${g.points||50}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi':'Rivela'),$('button',{class:'btn',disabled:cur.i<=0,onclick:()=>{cur.i--;cur.answer=false;render()}},'←'),$('button',{class:'btn',disabled:cur.i>=steps.length-1,onclick:()=>{cur.i++;cur.answer=false;render()}},'→')))}
function labors(g){const qs=g.questions?.length?g.questions:templates.labors().questions,items=Array.from({length:10},(_,i)=>qs[i]||{kind:'sfida',question:`Fatica ${i+1}`,options:[],answer:''});if(!cur.laborOpen)return $('div',{class:'labors-board-screen'},$('div',{class:'ppt-label'},'PUNTI'),$('div',{class:'labors-prompt-card'},g.topic||g.title||'LE DIECI FATICHE'),$('div',{class:'labors-number-grid'},...items.map((q,i)=>$('button',{class:`labors-number ${q.status==='correct'?'done':''}`,onclick:()=>{cur.i=i;cur.laborOpen=true;cur.answer=false;render()}},i+1))));const q=items[cur.i]||items[0],key=`labors-${cur.i}`,done=hasAwarded(key);return $('div',{class:'labors-question-screen'},$('div',{class:'ppt-label'},'PUNTI'),$('div',{class:'labors-question-card'},q.question),q.options?.length?$('div',{class:'labors-options'},...q.options.map((o,i)=>$('button',{class:'ppt-row-card'},`${String.fromCharCode(65+i)}: ${o}`))):null,$('div',{class:'host-actions'},$('button',{class:'btn success',disabled:done,onclick:()=>awardOnce(g.points||100,`${g.title}: fatica ${cur.i+1}`,key,()=>{q.status='correct'})},done?'Assegnata':`Corretta · +${g.points||100}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi':'Risposta'),$('button',{class:'btn ghost',onclick:()=>{cur.laborOpen=false;cur.answer=false;render()}},'Torna alle fatiche')),answer(`${q.answer||''}${q.explanation?' · '+q.explanation:''}`))}
function guillotine(g){return $('div',{class:'guillotine-screen'},$('h2',{},'GHIGLIOTTINA'),$('div',{class:'word-cloud'},...(g.words||[]).map(w=>$('div',{class:'ppt-button word'},w))),controls(g,g.answer,g.points||200))}
function legacyPass(g){const qs=g.questions||[],q=qs[cur.i]||qs[0],d=g.difficulty||'facile',pts=g.points?.[d]??5,bonus=g.bonus?.[d]??0,all=qs.length&&qs.every(x=>x.status==='correct');if(!q)return $('div',{class:'intro-screen'},'Nessuna domanda.');return $('div',{class:'pass-screen'},$('div',{class:'pass-wheel'},...qs.map((x,i)=>{const ang=(360/qs.length)*i-90;return $('button',{class:`pass-letter ${x.status==='correct'?'ok':x.status==='wrong'?'wrong':x.status==='pass'?'passed':''} ${i===cur.i?'current':''}`,style:`--angle:${ang}deg`,onclick:()=>{cur.i=i;cur.answer=false;render()}},x.letter)}),$('div',{class:'wheel-core'},$('strong',{},q.letter),$('span',{},d.toUpperCase()))),$('div',{class:'pass-question'},$('div',{class:'timer-box'},'00:50'),$('h2',{},q.question),$('div',{class:'host-actions'},$('button',{class:'btn success',onclick:()=>{q.status='correct';add(pts,`${g.title}: lettera ${q.letter}`)}},`Corretta · +${pts}`),$('button',{class:'btn danger',onclick:()=>{q.status='wrong';save();render()}},'Sbagliata'),$('button',{class:'btn warn',onclick:()=>{q.status='pass';save();render()}},'Passo'),all ? $('button',{class:'btn primary',onclick:()=>add(bonus,`${g.title}: bonus ${d}`)},`Bonus · +${bonus}`) : null,$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi':'Risposta')),answer(q.answer))) }
function legacyJeopardy(g){const cats=g.categories||[];if(cur.jeo){const c=cats[cur.jeo.c],cl=c?.clues?.[cur.jeo.q];if(cl)return $('div',{class:'jeopardy-question'},$('div',{class:'topic'},`${c.name} · ${cl.value} punti`),$('h2',{},cl.question),controls(g,cl.answer,cl.value,()=>{cl.used=true;cur.jeo=null;save()}),$('button',{class:'btn ghost',onclick:()=>{cur.jeo=null;render()}},'Torna al tabellone'))}return $('div',{class:'jeopardy-board'},...cats.map((c,ci)=>$('div',{class:'jeopardy-col'},$('div',{class:'jeopardy-cat'},c.name),...(c.clues||[]).map((cl,qi)=>$('button',{class:`jeopardy-cell ${cl.used?'used':''}`,disabled:cl.used,onclick:()=>{cur.jeo={c:ci,q:qi};cur.answer=false;render()}},cl.value))))) }
function legacySarabanda(g){return linear(g,g.songs||[],s=>$('div',{class:'sarabanda-screen'},$('h2',{},'SARABANDA'),audio(s.audio),$('div',{class:'host-actions'},$('button',{class:'btn success',onclick:()=>add(g.pointsTitle||25,`${g.title}: titolo`)},`Titolo · +${g.pointsTitle||25}`),$('button',{class:'btn success',onclick:()=>add(g.pointsArtist||25,`${g.title}: autore`)},`Autore · +${g.pointsArtist||25}`),$('button',{class:'btn primary',onclick:()=>add((g.pointsTitle||25)+(g.pointsArtist||25),`${g.title}: completa`)},'Completa · +50'),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta')),answer(`${s.title||'Titolo'} · ${s.artist||'Artista'}`)))}
function history(){return $('section',{class:'history-box'},$('h3',{},'Storico'),...(state.history.length?state.history.slice(0,7).map(h=>$('div',{class:'history-row'},$('span',{},h.playerName),$('small',{},h.reason),$('strong',{},`${h.points>0?'+':''}${h.points}`))):[$('p',{class:'muted'},'Nessun punto assegnato.')]))}
function admin(){const sel=$('select',{id:'type',onchange:preview});Object.entries(TYPES).forEach(([v,l])=>sel.append($('option',{value:v},l)));const title=$('input',{id:'title',value:'Nuovo minigioco',oninput:()=>{if(!editing)preview()}}),ta=$('textarea',{id:'json'});setTimeout(preview);return $('main',{class:'grid two'},$('section',{class:'panel stack'},$('h2',{},'Admin contenuti'),$('p',{class:'muted'},'Il gioco ora segue la struttura PowerPoint: home, HUD integrato nella slide, bottom scorebar e minigiochi in stile videogame.'),$('div',{class:'grid two'},$('label',{},'Titolo evento',$('input',{value:state.title||'',onchange:e=>{state.title=e.target.value;save();render()}})),$('label',{},'Sottotitolo',$('input',{value:state.subtitle||'',onchange:e=>{state.subtitle=e.target.value;save();render()}}))),$('div',{class:'grid two'},$('label',{},'Tipo minigioco',sel),$('label',{},'Titolo',title)),$('label',{},'Contenuto JSON',ta),$('div',{class:'row'},$('button',{class:'btn primary',onclick:saveEditor},editing?'Salva modifiche':'Crea minigioco'),$('button',{class:'btn',onclick:()=>{editing='';preview()}},'Nuovo da template'),$('button',{class:'btn',onclick:exportData},'Esporta JSON'),$('label',{class:'btn ghost'},'Importa JSON',$('input',{type:'file',accept:'application/json',style:'display:none',onchange:importData}))),playersAdmin(),libraryAdmin(),powersAdmin()),$('aside',{class:'panel stack'},$('h3',{},'Minigiochi salvati'),...state.games.map(g=>$('div',{class:'saved-game'},$('div',{},$('strong',{},g.title),$('small',{},label(g.type))),$('div',{class:'row'},$('button',{class:'btn small',onclick:()=>edit(g.id)},'Modifica'),$('button',{class:'btn small',onclick:()=>dup(g.id)},'Duplica'),$('button',{class:'btn small danger',onclick:()=>del(g.id)},'Elimina')))),$('h3',{},'Immagini riferimento repo'),$('div',{class:'reference-grid'},...REFERENCE_IMAGES.map(name=>$('a',{href:`public/reference-images/${encodeURIComponent(name)}`,target:'_blank',class:'ref-thumb'},$('img',{src:`public/reference-images/${encodeURIComponent(name)}`,alt:name}),$('span',{},name.replace(/^\d+\.\s*/,'').replace('.png',''))))))) }
function legacyPreview(){const type=document.getElementById('type')?.value||'guess',title=document.getElementById('title')?.value||'Nuovo minigioco',ta=document.getElementById('json');if(!ta)return;const g=templates[type]();g.title=title;g.menuTitle=title.toUpperCase();ta.value=JSON.stringify(g,null,2)}
function legacySaveEditor(){try{const g=JSON.parse(document.getElementById('json').value);g.id=g.id||id('game');g.title=document.getElementById('title').value.trim()||g.title;g.menuTitle=g.menuTitle||g.title?.toUpperCase();const i=state.games.findIndex(x=>x.id===(editing||g.id));i>=0?state.games[i]=g:state.games.unshift(g);gameId=g.id;editing='';save();toast('Minigioco salvato');render()}catch(e){toast('JSON non valido: '+e.message)}}
function edit(gid){const g=state.games.find(x=>x.id===gid);if(!g)return;editing=gid;render();document.getElementById('type').value=g.type;document.getElementById('title').value=g.title||'';document.getElementById('json').value=JSON.stringify(g,null,2)}
function legacyDup(gid){const g=clone(state.games.find(x=>x.id===gid));g.id=id('game');g.title+=' copia';g.menuTitle=(g.menuTitle||g.title).replace(' COPIA','')+' COPIA';state.games.unshift(g);save();render()}
function legacyDel(gid){const g=state.games.find(x=>x.id===gid);if(!g||!confirm(`Eliminare “${g.title}”?`))return;state.games=state.games.filter(x=>x.id!==gid);gameId=state.games[0]?.id;save();render()}
function playersAdmin(){return $('section',{class:'stack'},$('h3',{},'Giocatori'),$('div',{class:'row'},$('input',{id:'pname',placeholder:'Nome squadra o giocatore'}),$('button',{class:'btn success',onclick:()=>{const v=document.getElementById('pname').value.trim();if(!v)return toast('Inserisci un nome.');const p={id:id('p'),name:v.toUpperCase(),score:0};state.players.push(p);playerId=p.id;save();render()}},'Aggiungi')),...state.players.map(p=>$('div',{class:'score-card'},$('input',{value:p.name,onchange:e=>{p.name=e.target.value.toUpperCase();save();render()}}),$('input',{type:'number',value:p.score||0,onchange:e=>{p.score=Number(e.target.value||0);save();render()}}),$('button',{class:'btn danger',onclick:()=>{if(state.players.length<2)return toast('Deve restare almeno un giocatore.');state.players=state.players.filter(x=>x.id!==p.id);playerId=state.players[0]?.id;save();render()}},'Rimuovi'))))}
function libraryAdmin(){return $('section',{class:'stack'},$('h3',{},'Lista Anime / Argomenti'),$('textarea',{value:state.library.join('\n'),style:'min-height:160px',onchange:e=>{state.library=e.target.value.split('\n').map(x=>x.trim()).filter(Boolean);save();render()}}))}
function powersAdmin(){return $('section',{class:'stack'},$('h3',{},'Poteri'),$('textarea',{value:JSON.stringify(state.powers,null,2),style:'min-height:180px',onchange:e=>{try{state.powers=JSON.parse(e.target.value);save();toast('Poteri aggiornati')}catch(err){toast('JSON poteri non valido')}}}))}
function scores(){return $('main',{class:'grid two'},$('section',{class:'panel stack'},$('h2',{},'Gestione manuale punteggi'),$('p',{class:'muted'},'Stessa logica della slide PUNTI originale, ma modificabile e con storico.'),pointsScreen(),$('div',{class:'row'},$('button',{class:'btn danger',onclick:()=>{if(confirm('Azzerare tutti i punteggi?')){state.players.forEach(p=>p.score=0);state.history=[];save();render()}}},'Azzera tutto'),$('button',{class:'btn',onclick:()=>{state.history=[];save();render()}},'Svuota storico'))),$('aside',{class:'panel'},history()))}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=$('a',{href:url,download:`trivia-challenge-${new Date().toISOString().slice(0,10)}.json`});document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
function legacyImportData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=hydrate(JSON.parse(r.result));if(!s.games?.length||!s.players?.length)throw Error('Il file deve contenere games e players.');state=s;gameId=state.games[0].id;playerId=state.players[0].id;save();render();toast('Dati importati')}catch(err){toast('Import fallito: '+err.message)}};r.readAsText(f)}

function cleanNumber(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback}
function cleanText(value,fallback=''){const text=String(value??'').trim();return text||fallback}
function gameListField(type){return {guess:'rounds',bomb:'items',said:'questions',detail:'questions',quote:'questions',chain:'questions',labors:'questions',pass:'questions',jeopardy:'categories',sarabanda:'songs'}[type]}
function normalizePlayer(p,i){const name=cleanText(p?.name,`PLAYER ${i+1}`).toUpperCase();return {id:cleanText(p?.id,id('p')),name,score:cleanNumber(p?.score,0)}}
function normalizeHistoryItem(h){return {id:cleanText(h?.id,id('h')),playerName:cleanText(h?.playerName,'PLAYER'),points:cleanNumber(h?.points,0),reason:cleanText(h?.reason,'correzione'),at:cleanText(h?.at,new Date().toISOString())}}
function normalizePowers(value){return Array.isArray(value)&&value.length?value.map(p=>({player:cleanText(p?.player,'PLAYER'),name:cleanText(p?.name,'Potere'),text:cleanText(p?.text,'')})):powers}
function normalizeGame(g){
  if(!g||typeof g!=='object'||Array.isArray(g))throw Error('Ogni minigioco deve essere un oggetto JSON.');
  const type=cleanText(g.type);
  if(!templates[type])throw Error(`Tipo minigioco non supportato: ${type||'mancante'}.`);
  const base=templates[type](),field=gameListField(type),out={...base,...g};
  out.id=cleanText(out.id,id('game'));
  out.title=cleanText(out.title,base.title||label(type));
  out.menuTitle=cleanText(out.menuTitle,out.title.toUpperCase());
  if(field&&!Array.isArray(out[field]))throw Error(`${out.title}: il campo "${field}" deve essere una lista.`);
  if(type==='guess')out.rounds=out.rounds.map(r=>({...r,points:Array.isArray(r.points)?r.points.map(x=>cleanNumber(x,0)):base.rounds[0].points}));
  if(type==='bomb')out.pointsPerCorrect=cleanNumber(out.pointsPerCorrect,base.pointsPerCorrect);
  if(['said','detail','quote','chain','labors','guillotine'].includes(type))out.points=cleanNumber(out.points,base.points);
  if(type==='pass'){out.points={facile:cleanNumber(out.points?.facile,base.points.facile),medio:cleanNumber(out.points?.medio,base.points.medio),difficile:cleanNumber(out.points?.difficile,base.points.difficile)};out.bonus={facile:cleanNumber(out.bonus?.facile,base.bonus.facile),medio:cleanNumber(out.bonus?.medio,base.bonus.medio),difficile:cleanNumber(out.bonus?.difficile,base.bonus.difficile)}}
  if(type==='jeopardy')out.categories=out.categories.map(c=>({...c,clues:Array.isArray(c.clues)?c.clues.map(cl=>({...cl,value:cleanNumber(cl.value,0)})):[]}));
  if(type==='sarabanda'){out.pointsTitle=cleanNumber(out.pointsTitle,base.pointsTitle);out.pointsArtist=cleanNumber(out.pointsArtist,base.pointsArtist)}
  return out;
}
function hydrate(s){
  if(!s||typeof s!=='object'||Array.isArray(s))throw Error('Il file importato deve contenere un oggetto JSON.');
  const players=(Array.isArray(s.players)?s.players:[]).map(normalizePlayer);
  const games=(Array.isArray(s.games)?s.games:[]).map(normalizeGame);
  if(!players.length)throw Error('Il file deve contenere almeno un giocatore.');
  if(!games.length)throw Error('Il file deve contenere almeno un minigioco.');
  return {...s,title:cleanText(s.title,'TRIVIA CHALLENGE'),subtitle:cleanText(s.subtitle,'ANIME EDITION'),players,games,library:Array.isArray(s.library)&&s.library.length?s.library.map(x=>cleanText(x)).filter(Boolean):animeList,powers:normalizePowers(s.powers),history:(Array.isArray(s.history)?s.history:[]).map(normalizeHistoryItem).slice(0,120)};
}
function save(){localStorage.setItem(KEY,JSON.stringify(hydrate(state)))}
function add(points,reason){const p=player();if(!p)return toast('Crea un giocatore.');const delta=cleanNumber(points,0);p.score=cleanNumber(p.score,0)+delta;state.history.unshift({id:id('h'),playerName:p.name,points:delta,reason,at:new Date().toISOString()});state.history=state.history.slice(0,120);save();toast(`${p.name}: ${delta>0?'+':''}${delta}`);render()}
function media(src,alt='media'){if(!src)return $('span',{class:'muted'},'Media non configurato');const value=String(src),path=value.split(/[?#]/)[0];if(/\.(mp4|webm|mov)$/i.test(path))return $('video',{src:value,controls:true,playsinline:true});return $('img',{src:value,alt,loading:'lazy'})}
function awardId(key){return `${gameId}:${key}`}
function hasAwarded(key){return !!cur.awarded?.[awardId(key)]}
function markAwarded(key){cur.awarded={...(cur.awarded||{}),[awardId(key)]:true}}
function awardOnce(points,reason,key,before){if(key&&hasAwarded(key))return toast('Punti gia assegnati per questa risposta.');if(before?.()===false)return;if(key)markAwarded(key);add(points,reason)}
function preview(){if(editing)return;const type=document.getElementById('type')?.value||'guess',title=document.getElementById('title')?.value||'Nuovo minigioco',ta=document.getElementById('json');if(!ta)return;const g=templates[type]();g.title=title;g.menuTitle=title.toUpperCase();ta.value=JSON.stringify(g,null,2)}
function controls(g,ans,points,key,after){if(typeof key==='function'){after=key;key=`${g.id}:${cur.i}`}key=key||`${g.id}:${cur.i}`;const done=hasAwarded(key);return $('div',{class:'host-actions'},$('button',{class:'btn success',disabled:done,onclick:()=>awardOnce(points,`${g.title}: risposta corretta`,key,after)},done?'Assegnata':`Corretta · +${points}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta'),answer(ans))}
function guess(g){const rs=g.rounds||[],r=rs[cur.i]||rs[0];if(!r)return $('div',{class:'intro-screen'},'Nessun round.');const clues=(r.clues||[]).map(c=>typeof c==='string'?{label:'?',image:c}:c),shown=Math.min(cur.revealed,clues.length),pts=(r.points||[1000,500,250,50])[Math.max(0,shown-1)]||0,key=`guess-${cur.i}`,done=hasAwarded(key);return $('div',{class:'guess-screen'},$('div',{class:'guess-main'},$('div',{class:'guess-grid'},...clues.map((c,i)=>$('button',{class:`guess-tile ${i<shown?'revealed':'covered'}`,onclick:()=>{if(i>=shown){cur.revealed=Math.max(cur.revealed,i+1);render()}}},i<shown?media(c.image,`Indizio ${i+1}`):$('span',{},c.label||r.points?.[i]||'?')))),answer(r.answer),pager(rs.length)),$('aside',{class:'guess-award-panel'},$('div',{class:'guess-award-title'},'PUNTI'),$('div',{class:'guess-award-value'},shown?pts:'--'),$('div',{class:'guess-award-players'},...state.players.map(p=>$('button',{class:`guess-award-player ${p.id===playerId?'selected':''}`,disabled:shown===0||done,onclick:()=>awardOnce(pts,`${g.title}: ${shown} indizi`,key,()=>{playerId=p.id})},$('span',{},p.name),$('strong',{},done?'OK':`+${pts}`)))),$('div',{class:'guess-panel-actions'},$('button',{class:'btn primary',disabled:shown>=clues.length,onclick:()=>{cur.revealed++;render()}},'Rivela'),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta'))))}
function bomb(g){const key='bomb',sel=new Set(cur.selected||[]),items=g.items||[],ok=items.filter((it,i)=>sel.has(i)&&!it.isBomb).length,bad=items.filter((it,i)=>sel.has(i)&&it.isBomb).length,done=hasAwarded(key),total=ok*(g.pointsPerCorrect||50);return $('div',{class:'bomb-screen'},$('div',{class:'bomb-question'},g.question||'Evita le bombe.'),$('div',{class:'bomb-grid'},...items.map((it,i)=>$('button',{class:`bomb-tile ${sel.has(i)?(it.isBomb?'bomb':'ok'):''}`,onclick:()=>{sel.has(i)?sel.delete(i):sel.add(i);cur.selected=[...sel];render()}},it.image?media(it.image,it.label):$('span',{},it.label||`Elemento ${i+1}`)))), $('div',{class:'host-actions'},$('span',{class:'pill'},`Corrette ${ok}`),$('span',{class:'pill'},`Bombe ${bad}`),$('button',{class:'btn success',disabled:done,onclick:()=>awardOnce(total,`${g.title}: ${ok} elementi corretti`,key)},done?'Assegnata':`Assegna ${total} pt`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi bombe':'Mostra bombe')),cur.answer?$('div',{class:'answer on'},'Bombe: '+items.filter(x=>x.isBomb).map(x=>x.label).join(', ')):null)}
function pass(g){const qs=g.questions||[],q=qs[cur.i]||qs[0],d=g.difficulty||'facile',pts=g.points?.[d]??5,bonus=g.bonus?.[d]??0,all=qs.length&&qs.every(x=>x.status==='correct');if(!q)return $('div',{class:'intro-screen'},'Nessuna domanda.');const key=`pass-${q.letter||cur.i}`,bonusKey=`pass-bonus-${d}`,done=q.status==='correct'||hasAwarded(key),bonusDone=hasAwarded(bonusKey);return $('div',{class:'pass-screen'},$('div',{class:'pass-wheel'},...qs.map((x,i)=>{const ang=(360/qs.length)*i-90;return $('button',{class:`pass-letter ${x.status==='correct'?'ok':x.status==='wrong'?'wrong':x.status==='pass'?'passed':''} ${i===cur.i?'current':''}`,style:`--angle:${ang}deg`,onclick:()=>{cur.i=i;cur.answer=false;render()}},x.letter)}),$('div',{class:'wheel-core'},$('strong',{},q.letter),$('span',{},d.toUpperCase()))),$('div',{class:'pass-question'},$('div',{class:'timer-box'},'00:50'),$('h2',{},q.question),$('div',{class:'host-actions'},$('button',{class:'btn success',disabled:done,onclick:()=>awardOnce(pts,`${g.title}: lettera ${q.letter}`,key,()=>{q.status='correct'})},done?'Assegnata':`Corretta · +${pts}`),$('button',{class:'btn danger',onclick:()=>{q.status='wrong';save();render()}},'Sbagliata'),$('button',{class:'btn warn',onclick:()=>{q.status='pass';save();render()}},'Passo'),all ? $('button',{class:'btn primary',disabled:bonusDone,onclick:()=>awardOnce(bonus,`${g.title}: bonus ${d}`,bonusKey)},bonusDone?'Bonus assegnato':`Bonus · +${bonus}`) : null,$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi':'Risposta')),answer(q.answer))) }
function jeopardy(g){const cats=g.categories||[];if(cur.jeo){const c=cats[cur.jeo.c],cl=c?.clues?.[cur.jeo.q];if(cl){const key=`jeopardy-${cur.jeo.c}-${cur.jeo.q}`;return $('div',{class:'jeopardy-question'},$('div',{class:'topic'},`${c.name} · ${cl.value} punti`),$('h2',{},cl.question),controls(g,cl.answer,cl.value,key,()=>{cl.used=true;cur.jeo=null;save()}),$('button',{class:'btn ghost',onclick:()=>{cur.jeo=null;render()}},'Torna al tabellone'))}}return $('div',{class:'jeopardy-board'},...cats.map((c,ci)=>$('div',{class:'jeopardy-col'},$('div',{class:'jeopardy-cat'},c.name),...(c.clues||[]).map((cl,qi)=>$('button',{class:`jeopardy-cell ${cl.used?'used':''}`,disabled:cl.used,onclick:()=>{cur.jeo={c:ci,q:qi};cur.answer=false;render()}},cl.value))))) }
function sarabanda(g){
  const songs=Array.from({length:12},(_,i)=>g.songs?.[i]||{audio:'',title:`Titolo ${i+1}`,artist:'Artista'}),s=songs[cur.i]||songs[0],titlePts=g.pointsTitle||25,artistPts=g.pointsArtist||25,titleKey=`sarabanda-${cur.i}-title`,artistKey=`sarabanda-${cur.i}-artist`,titleDone=hasAwarded(titleKey),artistDone=hasAwarded(artistKey),remaining=(titleDone?0:titlePts)+(artistDone?0:artistPts);
  return $('div',{class:'sarabanda-board-screen'},
    $('div',{class:'ppt-label'},'PUNTI'),
    $('div',{class:'sarabanda-grid'},...songs.map((song,i)=>$('button',{class:`sarabanda-audio-card ${i===cur.i?'current':''}`,onclick:()=>{cur.i=i;cur.answer=false;render()}},song.audio?audio(song.audio):'AUDIO'))),
    $('div',{class:'sarabanda-answer-strip'},cur.answer?`${cleanText(s.title,'Titolo')} - ${cleanText(s.artist,'Artista')}`:'Risposta nascosta'),
    scorePods([titlePts,artistPts],`${g.title}: punti rapidi`),
    $('div',{class:'host-actions'},$('button',{class:'btn success',disabled:titleDone,onclick:()=>awardOnce(titlePts,`${g.title}: titolo`,titleKey)},titleDone?'Titolo assegnato':`Titolo · +${titlePts}`),$('button',{class:'btn success',disabled:artistDone,onclick:()=>awardOnce(artistPts,`${g.title}: autore`,artistKey)},artistDone?'Autore assegnato':`Autore · +${artistPts}`),$('button',{class:'btn primary',disabled:remaining===0,onclick:()=>{let total=0;if(!hasAwarded(titleKey)){markAwarded(titleKey);total+=titlePts}if(!hasAwarded(artistKey)){markAwarded(artistKey);total+=artistPts}if(!total)return toast('Punti gia assegnati per questa canzone.');add(total,`${g.title}: completa`)}},remaining===0?'Completa assegnata':`Completa · +${remaining}`),$('button',{class:'btn',onclick:()=>{cur.answer=!cur.answer;render()}},cur.answer?'Nascondi risposta':'Mostra risposta'))
  )
}
function saveEditor(){try{const raw=JSON.parse(document.getElementById('json').value);raw.id=raw.id||id('game');raw.title=document.getElementById('title').value.trim()||raw.title;raw.menuTitle=raw.menuTitle||raw.title?.toUpperCase();const g=normalizeGame(raw),i=state.games.findIndex(x=>x.id===(editing||g.id));i>=0?state.games[i]=g:state.games.unshift(g);gameId=g.id;editing='';save();toast('Minigioco salvato');render()}catch(e){toast('JSON non valido: '+e.message)}}
function dup(gid){const found=state.games.find(x=>x.id===gid);if(!found)return toast('Minigioco non trovato.');const g=clone(found);g.id=id('game');g.title+=' copia';g.menuTitle=(g.menuTitle||g.title).replace(' COPIA','')+' COPIA';state.games.unshift(normalizeGame(g));save();render()}
function del(gid){const g=state.games.find(x=>x.id===gid);if(!g)return;if(state.games.length<2)return toast('Deve restare almeno un minigioco.');if(!confirm(`Eliminare "${g.title}"?`))return;state.games=state.games.filter(x=>x.id!==gid);gameId=state.games[0]?.id;save();render()}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=hydrate(JSON.parse(r.result));state=s;gameId=state.games[0].id;playerId=state.players[0].id;save();render();toast('Dati importati')}catch(err){toast('Import fallito: '+err.message)}};r.readAsText(f)}
render();
